# Copyright 2021 Hewlett Packard Enterprise Development LP
---
- name: Set non-CAN access rules to k8s api gw
  command:  "{{item }}"
  with_items:
    - bash -c "iptables -F OUTPUT"
    - bash -c "iptables -A OUTPUT -p tcp -m multiport --dports {{api_gw_ports}} -d {{api_gw_ips}} -m owner --uid-owner root -j ACCEPT"
    - bash -c "iptables -A OUTPUT -p tcp -m multiport --dports {{api_gw_ports}} -d {{api_gw_ips}} -j DROP"
  when: api_gw_ips|length > 0

- block:
  - name: Show CAN
    debug:
      msg: "{{ customer_access_network }}"
    when: customer_access_network is defined

  - name: Set access rules to k8s api gw
    command:  "{{item }}"
    with_items:
      - bash -c "iptables -A OUTPUT -d {{customer_access_network}} -m owner --uid-owner root -j ACCEPT"
      - bash -c "iptables -A OUTPUT -d {{customer_access_network}} -j DROP"
    when: customer_access_network is defined

  when: uan_can_setup

- name: Read access rules to k8s api gw
  command:  bash -c "iptables -L -n --line-numbers"
  register: iptables_list
  when: api_gw_ips|length > 0

- name: List resutling iptables
  debug:
    msg: "{{ iptables_list.stdout_lines }}"
  when: iptables_list is defined