# Copyright 2020 Hewlett Packard Enterprise Development LP
# uan_interfaces tasks
---
- block:
  - name: Get NMN Services Network info from SLS
    local_action:
      module: uri
      url: http://cray-sls/v1/search/networks?name=MetalLB_NMN
      method: GET
    register: sls_nmn_svcs
    failed_when: sls_nmn_svcs.status != 200

  - name: Get NMN Services CIDR from SLS
    set_fact:
      nmn_svcs_cidr: "{{ sls_nmn_svcs.json[0].IPRanges[0] }}"

  - name: Get NMN Network info from SLS
    local_action:
      module: uri
      url: http://cray-sls/v1/search/networks?name=NMN
      method: GET
    register: sls_nmn
    failed_when: sls_nmn.status != 200

  - name: Get NMN CIDR from SLS
    set_fact:
      nmn_cidr: "{{ sls_nmn.json[0].IPRanges[0] }}"

  - name: Get NMN gateway
    set_fact:
      nmn_gateway: "{{ nmn_cidr | ipaddr('network/prefix') | ipaddr('next_usable') }}"

  - name: Configure ifcfg-nmn0
    copy:
      src: ifcfg-nmn0
      dest: /etc/sysconfig/network/ifcfg-nmn0
      owner: root
      group: root
      mode: '0644'

  - name: Configure iproute2 tables
    lineinfile:
      path: /etc/iproute2/rt_tables
      regexp: '^{{ item.pref }}\s+{{ item.name }}'
      line: "{{ item.pref }}       {{ item.name }}"
    loop: "{{ rt_tables }}"

  - name: Configure ifroute-nmn0
    template:
      src: ifroute-nmn0.j2
      dest: /etc/sysconfig/network/ifroute-nmn0
      owner: root
      mode: 0600

  - name: Tell DHCP client to not set default gateway
    lineinfile:
      path: /etc/sysconfig/network/dhcp
      regex: '^DHCLIENT_SET_DEFAULT_ROUTE='
      line: DHCLIENT_SET_DEFAULT_ROUTE="no"

  - name: Remove existing default route
    command: "ip route delete default"
    changed_when: result.rc != 0 or result.rc == 2
    failed_when: result.rc != 0 and result.rc != 2
    register: result

  # Configure CAN v2 - Uses external subnet on vlan007
  - include_tasks: can-v2.yml
    when: uan_can_setup 

  # Configure Customer defined interfaces, routes, and rules
  - include_tasks: customer_interfaces.yml

  when: not cray_cfs_image