# Copyright 2020 Hewlett Packard Enterprise Development LP
# uan_interfaces tasks
---
- block:
  - name: Get NMN Services Network info from SLS
    local_action:
      module: uri
      url: http://cray-sls/v1/search/networks?name=MetalLB_NMN
      method: GET
    register: sls_nmn_svcs
    failed_when: sls_nmn_svcs.status != 200

  - name: Get NMN Services CIDR from SLS
    set_fact:
      nmn_svcs_cidr: "{{ sls_nmn_svcs.json[0].IPRanges[0] }}"

  - name: Get NMN Network info from SLS
    local_action:
      module: uri
      url: http://cray-sls/v1/search/networks?name=NMN
      method: GET
    register: sls_nmn
    failed_when: sls_nmn.status != 200

  - name: Get NMN CIDR from SLS
    set_fact:
      nmn_cidr: "{{ sls_nmn.json[0].IPRanges[0] }}"

  - name: Get NMN gateway
    set_fact:
      nmn_gateway: "{{ nmn_cidr | ipaddr('network/prefix') | ipaddr('next_usable') }}"

  - name: Slurp in /etc/resolv.conf to get any DHCP added entries
    slurp:
      src: "/etc/resolv.conf"
    register: resolv_conf

  - name: Register /etc/resolv.conf contents
    set_fact:
      resolv: "{{ resolv_conf.content | b64decode }}"  

  - name: Parse existing nameservers from /etc/resolv.conf
    set_fact:
      uan_existing_nameservers: "{{ resolv | regex_findall( 'nameserver (\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3})\\b') }}"

  - name: Parse existing search domains from /etc/resolv.conf
    set_fact:
      uan_existing_search_domains: "{{ item.split() }}"
    loop: "{{ resolv | regex_findall( 'search (\\b(?:[a-zA-Z0-9])?(?:[a-zA-Z0-9-]{1,})?(?:\\.[a-zA-Z0-9-]{1,}){1,}\\b.*){1,}') }}"

  - name: Slurp in /etc/sysconfig/network/config to get any DHCP added entries
    slurp:
      src: "/etc/sysconfig/network/config"
    register: net_config

  - name: Register /etc/sysconfig/network/config contents
    set_fact:
      netconf: "{{ net_config.content | b64decode }}"  

  - name: Parse search domains from config list
    set_fact:
      uan_netconf_search_domains: "{{ item.split() }}"
    loop: "{{ netconf | regex_findall( 'NETCONFIG_DNS_STATIC_SEARCHLIST=\"(.*)\"') }}"

  - name: Parse nameservers from config list
    set_fact:
      uan_netconf_nameservers: "{{ item.split() }}"
    loop: "{{ netconf | regex_findall( 'NETCONFIG_DNS_STATIC_SERVERS=\"(.*)\"') }}"

  - name: Add existing search domains to uan_netconf_search_domains
    set_fact:
      uan_netconf_search_domains: "{{ uan_netconf_search_domains }} + [ item ]"
    when: (uan_existing_search_domains is defined) and (item not in uan_netconf_search_domains)
    loop: "{{ uan_existing_search_domains }}"

  - name: Add existing nameservers to uan_netconf_nameservers
    set_fact:
      uan_netconf_nameservers: "{{ uan_netconf_nameservers }} + [ item ]"
    when: (uan_existing_nameservers is defined) and (item not in uan_netconf_nameservers)
    loop: "{{ uan_existing_nameservers }}"

  - name: Add any customer defined search domains to uan_netconf_search_domains
    set_fact:
      uan_netconf_search_domains: "{{ uan_netconf_search_domains }} + [ item ]"
    when: item not in uan_netconf_search_domains
    loop: "{{ external_dns_searchlist }}"

  - name: Add any customer defined nameservers to uan_netconf_nameservers
    set_fact:
      uan_netconf_nameservers: "{{ uan_netconf_nameservers }} + [ item ]"
    when: item not in uan_netconf_nameservers
    loop: "{{ external_dns_servers }}"

  - name: Set DNS STATIC SEARCHLIST entries
    when: uan_netconf_search_domains is defined
    lineinfile:
      dest: /etc/sysconfig/network/config
      regex: '^NETCONFIG_DNS_STATIC_SEARCHLIST=\"(.*)\"$'
      line: "NETCONFIG_DNS_STATIC_SEARCHLIST=\"{{ uan_netconf_search_domains | join(' ') }}\""
      backrefs: yes

  - name: Set DNS STATIC SERVERS entries
    when: uan_netconf_nameservers is defined
    lineinfile:
      dest: /etc/sysconfig/network/config
      regex: '^NETCONFIG_DNS_STATIC_SERVERS=\"(.*)\"$'
      line: "NETCONFIG_DNS_STATIC_SERVERS=\"{{ uan_netconf_nameservers | join(' ') }}\""
      backrefs: yes

  - name: Generate updated /etc/resolv.conf by restarting wicked
    shell: "systemctl restart wicked;sleep 5"
    changed_when: result.rc == 0
    failed_when: result.rc != 0
    register: result

  - name: Configure ifcfg-nmn0
    copy:
      src: ifcfg-nmn0
      dest: /etc/sysconfig/network/ifcfg-nmn0
      owner: root
      group: root
      mode: '0644'

  - name: Configure iproute2 tables
    lineinfile:
      path: /etc/iproute2/rt_tables
      regexp: '^{{ item.pref }}\s+{{ item.name }}'
      line: "{{ item.pref }}       {{ item.name }}"
    loop: "{{ rt_tables }}"

  - name: Configure ifroute-nmn0
    template:
      src: ifroute-nmn0.j2
      dest: /etc/sysconfig/network/ifroute-nmn0
      owner: root
      mode: 0600

  - name: Tell DHCP client to not set default gateway
    lineinfile:
      path: /etc/sysconfig/network/dhcp
      regex: '^DHCLIENT_SET_DEFAULT_ROUTE='
      line: DHCLIENT_SET_DEFAULT_ROUTE="no"

  - name: Remove existing default route
    command: "ip route delete default"
    changed_when: result.rc != 0 or result.rc == 2
    failed_when: result.rc != 0 and result.rc != 2
    register: result

  # Configure CAN v2 - Uses external subnet on vlan007
  - include_tasks: can-v2.yml
    when: uan_can_setup 

  # Configure Customer defined interfaces, routes, and rules
  - include_tasks: customer_interfaces.yml

  when: not cray_cfs_image