# Copyright 2020-2021 Hewlett Packard Enterprise Development LP
# Dockerfile for image which holds the UAN image (squashfs) and Kiwi recipe
FROM artifactory.algol60.net/csm-docker/stable/cray-ims-load-artifacts:@ims_load_artifacts_image_tag@

# Copy the IMS import manifest
COPY manifest.yaml /

# Copy the image/recipe files
COPY build/output/*@product_version@* /
