# Copyright 2020 Hewlett Packard Enterprise Development LP
# Dockerfile for image which holds the UAN image (squashfs) and Kiwi recipe
FROM dtr.dev.cray.com/cray/cray-ims-load-artifacts:IMAGE_CRAY_IMS_LOAD_ARTIFACTS_TAG

# Use for testing/not in pipeline builds
#FROM dtr.dev.cray.com/cray/cray-ims-load-artifacts:latest

# Copy the IMS import manifest
COPY manifest.yaml /

# Copy the image/recipe files
COPY build/output/*@product_version@* /
