#
# MIT License
#
# (C) Copyright 2020-2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# Tasks for uan_disk_config role
---
- name: Check for available disks
  device_filter:
    device_data: "{{ ansible_devices }}"
    device_name_filter: "{{ uan_device_name_filter }}"
    device_name_exclude_filter: "{{ uan_device_name_exclude_filter }}"
    device_host_filter: "{{ uan_device_host_filter }}"
    device_host_exclude_filter: "{{ uan_device_host_exclude_filter }}"
    device_model_filter: "{{ uan_device_model_filter }}"
    device_model_exclude_filter: "{{ uan_device_model_exclude_filter }}"
    device_vendor_filter: "{{ uan_device_vendor_filter }}"
    device_vendor_exclude_filter: "{{ uan_device_vendor_exclude_filter }}"
    device_size_filter: "{{ uan_device_size_filter }}"
  register: uan_disk_options

- name: Fail if no disks are available
  fail:
    msg: No disks match the criteria given, and a disk is required for scratch/swap
  when:
    - uan_disk_options.devices == {}
    - uan_require_disk

- name: Select first available disk
  set_fact:
    uan_disk: "/dev/{{ uan_disk_options.devices | first }}"
  when:
    - uan_disk_options.devices != {}

- name: Spec {{ uan_disk }}
  stat:
    path: "{{ uan_disk }}"
  register: uan_disk_stat
  when:
    - uan_disk_options.devices != {}

- block:
  - name: Check if swap and scratch are mounted
    shell: "df | grep {{ item }} | rev | cut -d' ' -f 1 | rev"
    register: fs_check
    loop: [ "{{ uan_disk }}1", "{{ uan_disk }}2" ]

  - name: Quiesce filesystem, if mounted
    shell: "fuser -km {{ item.stdout }}"
    ignore_errors: yes
    when: item.stdout != '' and item.stdout not in ['/scratch', '/swap']
    loop: "{{ fs_check.results }}"

  - name: Unmount filesystem, if mounted
    shell: "umount -l {{ item.stdout }}"
    when: item.stdout != '' and item.stdout not in ['/scratch', '/swap']
    loop: "{{ fs_check.results }}"

  - name: Remove from fstab
    mount:
      path: "{{ item.stdout }}"
      state: absent
    when: item.stdout != '' and item.stdout not in ['/scratch', '/swap']
    loop: "{{ fs_check.results }}"

  - name: Create swap partition
    parted:
      device: "{{ uan_disk }}"
      number: 1
      state: present
      part_end: "50%"

  - name: Create scratch partition
    parted:
      device: "{{ uan_disk }}"
      number: 2
      state: present
      part_start: "50%"

  - name: Create filesystem for swap and scratch
    filesystem:
      fstype: ext4
      dev: "{{ item[0] }}"
      force: yes
    when: item[1].stdout == ''
    with_nested:
      - [ "{{ uan_disk }}1", "{{ uan_disk }}2" ]
      - "{{ fs_check.results }}"

  - name: Mount swap
    mount:
      path: "{{ uan_swap }}"
      src: "{{ uan_disk }}1"
      fstype: ext4
      state: mounted

  - name: Mount scratch
    mount:
      path: "{{ uan_scratch }}"
      src: "{{ uan_disk }}2"
      fstype: ext4
      state: mounted

  - name: Create swap space
    command: "{{ swap_dd_command }}"
    args:
      creates: "{{ uan_swap }}/{{ swap_file }}"
    register: swap_file_create

  - name: Set permissions on swap file.
    file:
      path: "{{ uan_swap }}/{{ swap_file }}"
      owner: root
      group: root
      mode: 0600
    when: swap_file_create is changed

  - name: Make swap file
    command: mkswap "{{ uan_swap }}/{{ swap_file }}"
    when: swap_file_create is changed

  - name: Add to fstab
    lineinfile:
      dest: /etc/fstab
      regexp: "{{ uan_swap }}/{{ swap_file }}"
      line: "{{ uan_swap }}/{{ swap_file }} none swap sw 0 0"

  - name: Turn swap on
    command: swapon -a

  - name: Set swappiness
    sysctl:
      name: vm.swappiness
      value: "{{ swap_swappiness }}"

  when:
    - uan_disk_options.devices != {}
    - uan_disk_stat.stat.isblk is defined
    - uan_disk_stat.stat.isblk == True
