# Copyright 2020-2021 Hewlett Packard Enterprise Development LP
# Defaults for uan_ldap role

# DO NOT SET VALUES IN THIS FILE.
# Override these values in the Ansible inventory or in a playbook.

# See the role README.md file for information about these variables.

uan_ldap_setup: yes

uan_ad_groups: []

uan_ldap_config: []

uan_pam_modules: []

# Vault access information to get encryption keys
uan_vault_url: "http://cray-vault.vault:8200"
uan_vault_role_file: /var/run/secrets/kubernetes.io/serviceaccount/namespace
uan_vault_jwt_file: /var/run/secrets/kubernetes.io/serviceaccount/token
uan_vault_path: secret/uan_ldap
uan_ldap_keys: []
