# Copyright 2020 Hewlett Packard Enterprise Development LP
# Tasks for the uan_packages role

- name: Configure UAN RPM Repos (SLES-based)
  zypper_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    repo: "{{ item.repo }}"
    priority: "{{ item.priority }}"
    state: present
    disable_gpg_check: "{{ item.disable_gpg_check | default('no') }}"
  when:
    - ansible_distribution == "SLES"
    - cray_cfs_image|default(false)|bool
  with_items: "{{ uan_sles15_repositories_add }}"

# UAN repos are generated during the release distribution creation and
# therefore repo metadata is not signed. Allow for the repo metadata to be
# unsigned, but still check the signature on individual packages.
- name: Allow unsigned repo metadata
  command: "zypper modifyrepo --gpgcheck-allow-unsigned-repo --all"
  args:
    warn: no  # Ansible's Zypper module does not provide this feature
  when:
    - ansible_distribution == "SLES"
    - cray_cfs_image|default(false)|bool

- name: Remove RPMs not needed by the UAN
  zypper:
    name: "{{ uan_sles15_packages_remove }}"
    state: absent
  when:
    - ansible_distribution == "SLES"
    - cray_cfs_image|default(false)|bool

- name: Install UAN RPMs (SLES-based)
  zypper:
    name: "{{ uan_sles15_packages_add }}"
    state: latest
    update_cache: yes
  when:
    - ansible_distribution == "SLES"
    - cray_cfs_image|default(false)|bool
  register: result
  until: result is not failed
  retries: 3
  delay: 3

