#
# MIT License
#
# (C) Copyright [2020-2022] Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# Tasks for the uan_packages role

- name: Check for csm.gpg_keys role
  local_action: stat path="{{ role_path | dirname }}/csm.gpg_keys"
  register: csm_gpg_keys

- name: Run csm.gpg_keys role, if it exists
  include_role:
    name: csm.gpg_keys
  when: csm_gpg_keys.stat.exists

- name: Configure UAN RPM Repos (SLES-based)
  zypper_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    repo: "{{ item.repo }}"
    priority: "{{ item.priority }}"
    state: present
    disable_gpg_check: "{{ item.disable_gpg_check | default(no) }}"
  when:
    - ansible_distribution == "SLES"
    - cray_cfs_image|default(false)|bool
  with_items: "{{ uan_sles15_repositories_add }}"

# UAN repos are generated during the release distribution creation and
# therefore repo metadata is not signed. Allow for the repo metadata to be
# unsigned, but still check the signature on individual packages.
- name: Allow unsigned repo metadata
  command: "zypper modifyrepo --gpgcheck-allow-unsigned-repo --all"
  args:
    warn: no  # Ansible's Zypper module does not provide this feature
  when:
    - ansible_distribution == "SLES"
    - cray_cfs_image|default(false)|bool

- name: Remove RPMs not needed by the UAN
  zypper:
    name: "{{ uan_sles15_packages_remove }}"
    state: absent
  when:
    - ansible_distribution == "SLES"
    - cray_cfs_image|default(false)|bool

- name: Install UAN RPMs (SLES-based)
  zypper:
    name: "{{ item.name }}"
    state: latest
    update_cache: yes
    disable_gpg_check: "{{ item.disable_gpg_check | default(no) }}"
  when:
    - ansible_distribution == "SLES"
    - cray_cfs_image|default(false)|bool
  register: result
  until: result is not failed
  retries: 3
  delay: 3
  loop: "{{ uan_sles15_packages_add }}"

