# Copyright 2020-2021 Hewlett Packard Enterprise Development LP
# Tasks for uan_ldap role
---
- name: Configure LDAP
  block:

  - name: Set ldap_port
    set_fact:
      ldap_port: 389

  - name: Override ldap_port if ldaps://
    set_fact:
      ldap_port: 636
    when: item.1 is regex('^ldaps://')
    with_subelements:
      - "{{ uan_ldap_config }}"
      - servers

  - name: Make sure we access the ldap servers first
    wait_for:
      host: "{{ item.1 | regex_replace('^ldaps?://', '') }}"
      port: "{{ ldap_port }}"
      state: started
      delay: 0
      timeout: 3
    with_subelements:
      - "{{ uan_ldap_config }}"
      - servers

  - name: Make nscd.conf compatible with sssd
    replace:
      path: /etc/nscd.conf
      regexp: '(^[ \t]+enable\-cache[ \t]+{{ item }}[ \t]+)yes'  
      replace: '\1no'
    with_items:
      - passwd
      - group
      - netgroup
      - services

  - name: Configure pam to use sss and enable mkhomedir
    when: not cray_cfs_image|default(false)
    command: "pam-config -a --sss --mkhomedir"

  - name: Test if /etc/pam.d/<module> is a symlink
    when: uan_pam_modules is defined
    stat:
      path: "/etc/pam.d/{{ item.name }}"
    register: links
    loop: "{{ uan_pam_modules }}"
      
  - name: Remove symlink of /etc/pam.d/<module> from /etc/pam.d/<module>-pc
    when: item.stat.islnk
    file: 
      path: "/etc/pam.d/{{ item.item.name }}"
      state: absent
    loop: "{{ links.results }}"

  - name: Copy /etc/pam.d/<module>-pc to /etc/pam.d/<module>
    when: item.stat.islnk
    shell: "cp /etc/pam.d/{{ item.item.name}}-pc /etc/pam.d/{{ item.item.name }}"
    changed_when: result.rc == 0
    failed_when: result.rc != 0
    register: result
    loop: "{{ links.results }}"

  - name: Add lines to /etc/pam.d/<module>
    when: uan_pam_modules is defined
    lineinfile:
      path: "/etc/pam.d/{{ item.0.name }}"
      regexp: "(^{{ item.1 }})"
      line: "{{ item.1 }}"
    with_subelements:
      - "{{ uan_pam_modules }}"
      - lines

  - name: Generate sssd.conf
    template:
      src: sssd.conf.j2
      dest: /etc/sssd/sssd.conf
      owner: root
      group: root
      mode: 0600

  - name: Start nscd and enable
    when: not cray_cfs_image|default(false)
    service:
      name: nscd
      state: restarted
      enabled: true

  - name: Start and enable sssd
    when: not cray_cfs_image|default(false)
    service:
      name: sssd
      state: restarted
      enabled: true

  - name: Copy over nsswitch.conf
    template:
      src: nsswitch.conf.j2
      dest: /etc/nsswitch.conf
      backup: yes

  - name: Generate new access.conf
    template:
      src: templates/access.conf.j2
      dest: /etc/security/access.conf
      backup: yes
      owner: root
      group: root
      mode: 0644

  when:
    - uan_ldap_setup
    - uan_ldap_config
    - not cray_cfs_image|default(false)
