---
- name: Configure LDAP
  block:
# -----------------------------------------------------------------------------
# TODO: remove this section when a sufficient resolution to CASMCMS-4156 comes about
  - name: WAR create temporary workarea for customer_var.yml
    tempfile:
      state: directory
      suffix: customer_var_yml
      path: "/tmp"
    register: customer_var_yml_dir
    run_once: true

  - name: WAR copy customer_var.yml from NCN host to Ansible master
    fetch:
      src: /opt/cray/crayctl/ansible_framework/customer_runbooks/customer_var.yml
      dest: "{{ customer_var_yml_dir.path }}/customer_var.yml"
      flat: yes
    delegate_to: "{{ vars_yml_src_server }}"
    run_once: true

  - name: WAR read in variables from customer_var.yml
    include_vars:
      file: "{{ customer_var_yml_dir.path }}/customer_var.yml"
      name: imported_customer_var
    run_once: true

  - name: WAR remove temporary workarea
    file:
      state: absent
      path: "{{ customer_var_yml_dir.path }}"
    run_once: true

  - name: Make sure we access the ldap servers first
    wait_for:
      host: "{{ item | regex_replace('^ldap://', '') }}"
      port: 389
      state: started
      delay: 0
      timeout: 3
    loop: "{{ imported_customer_var.ldap_servers }}"

  - name: Install sssd and related packages
    zypper:
      name: 
        - sssd
        - sssd-ldap
        - sssd-krb5-common
        - sssd-tools
        - pam_ldap
        - nss_ldap
      state: present 

  - name: Generate sssd.conf
    template:
      src: sssd.conf.j2
      dest: /etc/sssd/sssd.conf
      owner: root
      group: root
      mode: 0600

  - name: Configure pam to use sss and enable mkhomedir
    command: "pam-config -a --sss --mkhomedir"

  - name: Disable nscd and stop
    service:
      name: nscd
      state: stopped
      enabled: false

  - name: Start and enable sssd
    service:
      name: sssd
      state: restarted
      enabled: true

  - name: Copy over nsswitch.conf
    copy:
      src: nsswitch.conf
      dest: /etc/nsswitch.conf
      backup: yes

  - name: Generate new access.conf
    template:
      src: templates/access.conf.j2
      dest: /etc/security/access.conf
      backup: yes
      owner: root
      group: root
      mode: 0644

  when:
    - imported_customer_var.ldap_servers is defined
    - imported_customer_var.domain is defined
    - imported_customer_var.search_base is defined
    - not cray_cfs_image
