# Copyright 2020 Hewlett Packard Enterprise Development LP
# Tasks for uan_ldap role
---
- name: Configure LDAP
  block:

  - name: Set ldap_port
    set_fact:
      ldap_port: 389

  - name: Override ldap_port if ldaps://
    set_fact:
      ldap_port: 636
    when: item.1 is regex('^ldaps://')
    with_subelements:
      - "{{ uan_ldap_config }}"
      - servers

  - name: Make sure we access the ldap servers first
    wait_for:
      host: "{{ item.1 | regex_replace('^ldaps?://', '') }}"
      port: "{{ ldap_port }}"
      state: started
      delay: 0
      timeout: 3
    with_subelements:
      - "{{ uan_ldap_config }}"
      - servers

  - name: Make nscd.conf compatible with sssd
    replace:
      path: /etc/nscd.conf
      regexp: '(^[ \t]+enable\-cache[ \t]+{{ item }}[ \t]+)yes'  
      replace: '\1no'
    with_items:
      - passwd
      - group
      - netgroup
      - services

  - name: Generate sssd.conf
    template:
      src: sssd.conf.j2
      dest: /etc/sssd/sssd.conf
      owner: root
      group: root
      mode: 0600

  - name: Configure pam to use sss and enable mkhomedir
    when: not cray_cfs_image|default(false)
    command: "pam-config -a --sss --mkhomedir"

  - name: Disable nscd and stop
    when: not cray_cfs_image|default(false)
    service:
      name: nscd
      state: stopped
      enabled: false

  - name: Start and enable sssd
    when: not cray_cfs_image|default(false)
    service:
      name: sssd
      state: restarted
      enabled: true

  - name: Copy over nsswitch.conf
    template:
      src: nsswitch.conf.j2
      dest: /etc/nsswitch.conf
      backup: yes

  - name: Generate new access.conf
    template:
      src: templates/access.conf.j2
      dest: /etc/security/access.conf
      backup: yes
      owner: root
      group: root
      mode: 0644

  when:
    - uan_ldap_config
