# Copyright 2020 Hewlett Packard Enterprise Development LP
# Defaults for uan_interfaces role
---
## uan_can_setup
# Set uan_can_setup to 'yes' if the site will
# use the Shasta CAN network for user access to
# UAN/Application nodes.
uan_can_setup: no

## Customer defined networks ifcfg-X
# customer_uan_interfaces is as list of interface names used for constructing
# ifcfg-<customer_uan_interfaces.name> files.  The setting dictionary is where
# any desired ifcfg fields are defined.  The field name will be converted to 
# uppercase in the generated ifcfg-<name> file.
#
# NOTE: Interfaces should be defined in order of dependency.
#
## Example ifcfg fields, not exhaustive:
#  bootproto: ''
#  device: ''
#  dhcp_hostname: ''
#  ethtool_opts: ''
#  gateway: ''
#  hwaddr: ''
#  ipaddr: ''
#  master: ''
#  mtu: ''
#  peerdns: ''
#  prefixlen: ''
#  slave: ''
#  srcaddr: ''
#  startmode: ''
#  userctl: ''
#  bonding_master: ''
#  bonding_module_opts: ''
#  bonding_slave0: ''
#  bonding_slave1: ''
# 
# customer_uan_interfaces:
#   - name: "net1"
#     settings:
#       bootproto: "static"
#       device: "net1"
#       ipaddr: "1.2.3.4"
#       startmode: "auto"
#   - name: "net2"
#     settings:
#       bootproto: "static"
#       device: "net2"
#       ipaddr: "5.6.7.8"
#       startmode: "auto"
customer_uan_interfaces: []

## Customer defined networks ifroute-X
# customer_uan_routes is as list of interface routes used for constructing
# ifroute-<customer_uan_routes.name> files.  
# 
# customer_uan_routes:
#   - name: "net1"
#     routes:
#       - "10.92.100.0 10.252.0.1 255.255.255.0 -"
#       - "10.100.0.0 10.252.0.1 255.255.128.0 -"
#   - name: "net2"
#     routes:
#       - "default 10.103.8.20 255.255.255.255 - table 3"
#       - "10.103.8.128/25 10.103.8.20 255.255.255.255 net2"
customer_uan_routes: []

## Customer defined networks ifrule-X
# customer_uan_rules is as list of interface rules used for constructing
# ifrule-<customer_uan_routes.name> files.  
# 
# customer_uan_rules:
#   - name: "net1"
#     rules:
#       - "from 10.1.0.0/16 lookup 1"
#   - name: "net2"
#     rules:
#       - "from 10.103.8.0/24 lookup 3"
customer_uan_rules: []

## Customer defined networks global routes
# customer_uan_global_routes is as list of global routes used for constructing
# the "routes" file.  
# 
# customer_uan_global_routes:
#   - routes: 
#       - "10.92.100.0 10.252.0.1 255.255.255.0 -"
#       - "10.100.0.0 10.252.0.1 255.255.128.0 -"
customer_uan_global_routes: []

## /etc/resolv.conf customer configurable fields
# Examples of usage format.
#
# external_dns_searchlist:
#   - 'my.domain.com'
#   - 'my.other.domain.com'
# external_dns_servers:
#   - '1.2.3.4'
#   - '5.6.7.8'
external_dns_searchlist:
  - ''
external_dns_servers:
  - ''
