# Copyright 2020-2021 Hewlett Packard Enterprise Development LP
# Defaults for uan_interfaces role

# DO NOT SET VALUES IN THIS FILE.
# Override these values in the Ansible inventory or in a playbook.

# See the role README.md file for information about these variables.

---
uan_can_setup: no

# SLS Network names
sls_nmn_name: "NMN"
sls_nmn_svcs_name: "NMNLB"
sls_mnmn_svcs_name: "NMN_MTN"
sls_can_name: "CAN"

# Example ifcfg fields available, not exhaustive:
#  bootproto: ''
#  device: ''
#  dhcp_hostname: ''
#  ethtool_opts: ''
#  gateway: ''
#  hwaddr: ''
#  ipaddr: ''
#  master: ''
#  mtu: ''
#  peerdns: ''
#  prefixlen: ''
#  slave: ''
#  srcaddr: ''
#  startmode: ''
#  userctl: ''
#  bonding_master: ''
#  bonding_module_opts: ''
#  bonding_slave0: ''
#  bonding_slave1: ''

customer_uan_interfaces: []

customer_uan_routes: []

customer_uan_rules: []

customer_uan_global_routes: []

external_dns_searchlist:
  - ''
external_dns_servers:
  - ''
