# Copyright 2020 Hewlett Packard Enterprise Development LP
# Defaults for uan_interfaces role
---
rt_tables:
  - pref: '1'
    name: rt_smnet
  - pref: '2'
    name: rt_mtl
  - pref: '3'
    name: rt_can

## ifcfg-X fields
bootproto: ''
device: ''
dhcp_hostname: ''
ethtool_opts: ''
gateway: ''
hwaddr: ''
ipaddr: ''
master: ''
mtu: ''
peerdns: ''
prefixlen: ''
slave: ''
srcaddr: ''
startmode: ''
userctl: ''
bonding_master: ''
bonding_module_opts: ''
bonding_slave0: ''
bonding_slave1: ''

## /etc/resolv.conf customer configurable fields
# Examples of usage format.
#
# external_dns_searchlist:
#   - 'my.domain.com'
#   - 'my.other.domain.com'
# external_dns_servers:
#  - '1.2.3.4'
#  - '5.6.7.8'
external_dns_searchlist:
  - ''
external_dns_servers:
  - ''