# Copyright 2020-2021 Hewlett Packard Enterprise Development LP
# Defaults for uan_interfaces role

# DO NOT SET VALUES IN THIS FILE.
# Override these values in the Ansible inventory or in a playbook.

# See the role README.md file for information about these variables.

---
uan_can_setup: no

# Example ifcfg fields available, not exhaustive:
#  bootproto: ''
#  device: ''
#  dhcp_hostname: ''
#  ethtool_opts: ''
#  gateway: ''
#  hwaddr: ''
#  ipaddr: ''
#  master: ''
#  mtu: ''
#  peerdns: ''
#  prefixlen: ''
#  slave: ''
#  srcaddr: ''
#  startmode: ''
#  userctl: ''
#  bonding_master: ''
#  bonding_module_opts: ''
#  bonding_slave0: ''
#  bonding_slave1: ''

customer_uan_interfaces: []

customer_uan_routes: []

customer_uan_rules: []

customer_uan_global_routes: []

external_dns_searchlist:
  - ''
external_dns_servers:
  - ''

## /etc/iproute2/rt_tables
# These values setup the routing tables on the UAN
# to work in the system networking environment.
rt_tables:
  - pref: '1'
    name: rt_smnet
  - pref: '2'
    name: rt_mtl
  - pref: '3'
    name: rt_can
