---
vars_yml_src_server: ncn-w001

rt_tables:
  - pref: '1'
    name: rt_smnet
  - pref: '2'
    name: rt_mtl
  - pref: '3'
    name: rt_can

bootproto: ''
device: ''
dhcp_hostname: ''
ethtool_opts: ''
gateway: ''
hwaddr: ''
ipaddr: ''
master: ''
mtu: ''
peerdns: ''
prefixlen: ''
slave: ''
srcaddr: ''
startmode: ''
userctl: ''
bonding_master: ''
bonding_module_opts: ''
bonding_slave0: ''
bonding_slave1: ''
