# Copyright 2020 Hewlett Packard Enterprise Development LP
# Defaults for uan_interfaces role
---
customer_access_gateway: ""  # ex. 10.102.14.0/24
customer_access_network: ""  # ex. 10.102.14.20
customer_access_metallb_address_pool: ""  # ex. 10.102.14.128/25

rt_tables:
  - pref: '1'
    name: rt_smnet
  - pref: '2'
    name: rt_mtl
  - pref: '3'
    name: rt_can

bootproto: ''
device: ''
dhcp_hostname: ''
ethtool_opts: ''
gateway: ''
hwaddr: ''
ipaddr: ''
master: ''
mtu: ''
peerdns: ''
prefixlen: ''
slave: ''
srcaddr: ''
startmode: ''
userctl: ''
bonding_master: ''
bonding_module_opts: ''
bonding_slave0: ''
bonding_slave1: ''
