#!/usr/bin/env ansible-playbook
# Copyright 2020-2021 Hewlett Packard Enterprise Development LP
# Top-level site.yml for User Access Nodes
- hosts: Application_UAN
  gather_facts: yes
  any_errors_fatal: true
  remote_user: root


  tasks:
    - name: Pause to allow Ansible debugging
      pause:
        minutes: 30000

