#
# MIT License
#
# (C) Copyright 2020-2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
#!/usr/bin/env ansible-playbook
# Top-level site.yml for User Access Nodes
- hosts: Application_UAN
  gather_facts: yes
  any_errors_fatal: true
  remote_user: root

  pre_tasks:
    - name: Disallow login to the UANs during post-boot configuration
      file:
        path: /etc/nologin
        owner: root
        group: root
        mode: 0644
        state: touch
      when: not cray_cfs_image and uan_login_config_protect|default(true)

  post_tasks:
    - name: Allow user logins to the UANs after configuration
      file:
        path: /etc/nologin
        state: absent
      when: not cray_cfs_image and uan_login_config_protect|default(true)

  roles:

    # UAN-specific configuration
    - { role: uan_packages,       when: cray_cfs_image|default(false)|bool }
    - { role: uan_shadow,         when: cray_cfs_image|default(false)|bool }
    - { role: uan_motd,           when: cray_cfs_image|default(false)|bool }
    - { role: uan_disk_config,    when: not cray_cfs_image|default(false)|bool }
    - { role: uan_interfaces,     when: not cray_cfs_image|default(false)|bool }
    - { role: uan_ldap,           when: not cray_cfs_image|default(false)|bool }
    - { role: uan_hardening,      when: not cray_cfs_image|default(false)|bool }

    # Rebuild initrd for image customization
    - { role: rebuild-initrd,     when: cray_cfs_image|default(false)|bool }

- hosts: Compute
  gather_facts: yes
  any_errors_fatal: true
  remote_user: root

  roles:
    - role: uan_interfaces
      when:
        - not cray_cfs_image|default(false)|bool
        - uan_can_setup
    - { role: uan_hardening,  when: not cray_cfs_image|default(false)|bool }
