#!/usr/bin/env ansible-playbook
# Copyright 2020-2021 Hewlett Packard Enterprise Development LP
# Top-level site.yml for User Access Nodes
- hosts: Application_UAN
  gather_facts: yes
  any_errors_fatal: true
  remote_user: root


  pre_tasks:
    - name: Disallow login to the UANs during post-boot configuration
      file:
        path: /etc/nologin
        owner: root
        group: root
        mode: 0644
        state: touch
      when: not cray_cfs_image and uan_login_config_protect|default(true)

  post_tasks:
    - name: Allow user logins to the UANs after configuration
      file:
        path: /etc/nologin
        state: absent
      when: not cray_cfs_image and uan_login_config_protect|default(true)

  roles:

    # Standard UNIX configuration
    - rsyslog
    - localtime
    - ntp
    - limits
    - kdump

    # Allow trust of CSM generated keys for elective passwordless SSH during image customization
    - role: trust-csm-ssh-keys
      when: cray_cfs_image|default(false)|bool

    # DVS/LNET/FS
    - overlay-preload
    - role: cray_lnet_load
      when: cray_cfs_image|default(false)|bool
    - role: cray_dvs_load
      when: cray_cfs_image|default(false)|bool

    # UAN-specific configuration
    - role: ca-cert
    - role: uan_shadow
    - role: uan_disk_config
      when: not cray_cfs_image
    - role: uan_packages
    - role: uan_interfaces
      when: not cray_cfs_image
    - role: uan_motd
    - role: uan_ldap

    # Nvidia developer toolkit
    - role: cray_nvidia_customize  # cf-cme-sysconfig
      when: gpu is defined and gpu|lower == "nvidia" and cray_cfs_image

    # Filesystem mounts
    - role: configure_fs

    # Rebuild initrd for image customization
    - role: rebuild-initrd
      when: cray_cfs_image | default(false) | bool

  tasks:

  - import_tasks: playbooks/nvidia_deploy.yml
    when: gpu is defined and gpu|lower == "nvidia" and (not cray_cfs_image | default(false))

