apiVersion: v1
description: "Kubernetes resources for cray-uan-install"
name: "cray-uan-install"
home: "scms/uan"
version: 1.1.44
keywords:
  - uan
  - cfs
  - ims
  - kiwi
sources:
  - "https://stash.us.cray.com/projects/SCMS/repos/uan/browse"
maintainers:
  - name: keopp
    email: jeffrey.keopp@hpe.com
