# Copyright 2020-2021 Hewlett Packard Enterprise Development LP
#
#   @***@ variables in this file are sed replaced using this repository's
#   runBuildPrep-config-framework.sh script.
#

# For products that import Ansible configuration content
cray-import-config:
  config_image:
    name: cray-uan-config
    # tag: should be specified in the UAN manifest; see SCMS/uan-product-stream repository

  import_job:
    CF_IMPORT_GITEA_REPO: "uan-config-management"
    CF_IMPORT_PRODUCT_NAME: "uan"
    # CF_IMPORT_PRODUCT_VERSION: should be specified in the UAN manifest; see SCMS/uan-product-stream repository

