#
# (C) Copyright 2023 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
- name: Creates directory for config for sshd_{{ item.name }}
  file:
    path: "{{ item.config_path | default('/etc/ssh/uan') }}"
    state: directory
    recurse: yes

- name: Set variables necessary for generating SSHD config sshd_{{ item.name }}
  set_fact:
    sshd_name: "{{ item.name }}"
    sshd_port: "{{ item.port }}"
    sshd_config: "{{ item.config | default('') }}"

- name: Generate SSHD config for sshd_{{ item.name }}
  template:
    src: roles/uan_sshd/templates/sshd_config.j2
    dest: "{{ item.config_path | default('/etc/ssh/uan') }}/sshd_{{ item.name }}_config"
    owner: root
    group: root
    mode: 0600
    backup: yes

- name: Copy connect_to_uai.sh ForceCommand script to {{ item.config_path | default('/etc/ssh/uan') }}
  copy:
    src: connect_to_uai.sh
    dest: "{{ item.config_path | default('/etc/ssh/uan') }}/connect_to_uai.sh"
    owner: root
    group: root
    mode: '0600'
    backup: yes

- name: Generate SSHD systemd unit file for sshd_{{ item.name }}
  template:
    src: roles/uan_sshd/templates/sshd.service.j2
    dest: "/usr/lib/systemd/system/sshd_{{ item.name }}.service"
    owner: root
    group: root
    mode: 0600
    backup: yes

- name: Set state of SSHD for sshd_{{ item.name }} to {{ item.state | default('started') }}
  service:
    name: sshd_{{ item.name }}
    state: "{{ item.state | default('started') }}"
